matrix:
  include:

    - language: node_js
      dist: trusty
      sudo: required
      node_js:
        - stable
      addons:
        chrome: stable
      branches:
        only:
          - master
      before_script:
          - chmod -R a+x scripts
          - npm install -g @angular/cli
          - npm install -g firebase-tools
      script:
          - ./scripts/ionic-build.bat
          - ./scripts/ionic-publish-firebase.bat
        
notifications:
  email:
    on_success: never
    on_failure: always