  - stage: server
    language: csharp
    dist: trusty
    sudo: required
    mono: none
    dotnet: 2.1
    branches:
        only:
            - master
    before_script:
        - chmod -R a+x scripts
    script:
        - ./scripts/dotnet-build.bat
        - ./scripts/dotnet-test.bat
        - ./scripts/dotnet-publish.bat
        - ./scripts/docker-publish-travis.bat
        - ./scripts/docker-publish-heroku.bat
    after_success:
        - ./scripts/after-success.bat
    notifications:
        email:
            on_success: never
            on_failure: always

  - stage: ui
    language: node_js
    dist: trusty
    sudo: required
    node_js: "6.9.0"
    branches:
        only:
            - master
    before_script: 
        - npm install
    script:
        - ./scripts/ionic-build.bat
        - ./scripts/ionic-publish-firebase.bat
        
    notifications:
        email:
            on_success: never
            on_failure: always
        