matrix:
  include:
    - language: csharp
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1
      branches:
          only:
              - master
      before_script:
          - chmod -R a+x scripts
      script:
          - ./scripts/dotnet-build.bat
          - ./scripts/dotnet-test.bat
          - ./scripts/dotnet-publish.bat
          - ./scripts/docker-publish-travis.bat
          - ./scripts/docker-publish-heroku.bat
          - ./scripts/docker-publish-heroku-release.bat
      after_success:
          - ./scripts/after-success.bat      
      
#    - language: node_js
#      dist: trusty
#      sudo: required
#      node_js:
#        - stable
#      addons:
#        chrome: stable
#      branches:
#        only:
#          - master
#      before_script:
#          - chmod -R a+x scripts
#          - npm install -g @angular/cli
#          - npm install -g firebase-tools
#      script:
#          - ./scripts/ionic-build.bat
#          - ./scripts/ionic-publish-firebase.bat
        
notifications:
  email:
    on_success: never
    on_failure: always