dist: trusty
sudo: required

matrix:
    include:
        - language: csharp
            mono: none
            dotnet: 2.1
        - language: node_js
            node_js:
                - "6.9.0"
        
branches:
    only:
        - master
before_script:
    - chmod -R a+x scripts
    - npm install
script:
    - ./scripts/dotnet-build.bat
    - ./scripts/dotnet-test.bat
    - ./scripts/dotnet-publish.bat
    - ./scripts/docker-publish-travis.bat
    - ./scripts/docker-publish-heroku.bat
    - ./scripts/ionic-build.bat
    - ./scripts/ionic-publish-firebase.bat    
after_success:
    - ./scripts/after-success.bat
notifications:
    email:
        on_success: never
        on_failure: always
        