import { Lang } from '../models/Lang';

export class En {
    public static En: Lang = {
        // Side menu
        menuMain: 'Main',
        menuOrganizations: 'Organizations',
        menuProjects: 'Projects',
        menuSavedProjects: 'Saved projects',
        menuSelectedProjects: 'Selected projects',
        menuCreatedProjects: 'Created projects',
        menuNewProject: 'New project',
        menuCalendar: 'Calendar',
        menuAboutUs: 'About us',
        menuPrivacyPolicy: 'Privacy policy',
        menuLogin: 'Login',
        menuRegistration: 'Registration',
        menuSettings: 'Settings',
        menuMenu: 'Menu',
        menuLogout: 'Logout',
        // Main page
        mainTitle: 'Volunteering system',
        mainEvents: 'Upcoming events',
        mainWantedOrganizations: 'Most wanted organizations',
        mainStart: 'Starts',
        //About us page
        aboutTitle: 'Shortly about us',
        aboutParag1: 'Platypus offers anyone an opportunity to immerse themselves in a community, working side by side with local leaders and tackle the most pressing challenges in Lithuania. Our mission is to help organizations all over Lithuania by providing them with manpower and funds needed in order to combat challenges facing our county‘s communities. We hope:',
        aboutParag2: "give something back to an organisation that has impacted on a person's life, either directly or indirectly",
        aboutParag3: 'make a difference to the lives of others',
        aboutParag4: 'help the environment',
        aboutParag5: 'help others less fortunate or without a voice feel valued and part of a team',
        aboutParag6: 'When you look at the reasons why volunteering is important, it’s not only about the impacts we can make in the lives of those less fortunate but the role it can play in making us more tolerant individuals and giving towards the global community. Each of us should be willing to offer our own time and expect nothing in return.',
        aboutTitle2: 'Why?',
        aboutVisit: 'Visit and find out more',
        aboutOpinion: 'Your opinion is important for us!',
        aboutButtonComment: 'Leave comment!',
        aboutButtonVideo: 'Watch video',
        aboutEnterEmail: 'Enter email',
        aboutFeelFree: 'Feel free to contact us',
        aboutComment: 'Comment',
        aboutRequired: 'Required field',
        aboutAlertCommentHeader: 'Thank you',
        aboutAlertCommentMessage: 'Your email has been submited',
        aboutSourceHeader: 'Want to know more?',
        aboutSourceMessage: 'Click confirm if you want to navigate to this page in a new tab',

        //Alert cancel and comfirm
        alertCancel: 'Cancel',
        alertConfirm: 'Confirm',
        toastClose: 'Close',
        //Login page
        loginWelcome: 'Welcome!',
        loginFieldset: 'Log in',
        loginUsername: 'Username',
        loginPassword: 'Password',
        loginForgot: 'Forgot you password?',
        loginButton: 'Sign in',
        loginNewHere: 'New here?',
        loginSignUp: 'Sing Up',
        loginResetPasswordMessage: 'Enter your email address to send a reset password link',
        loginRequiredField: 'Required field, must contain at least 5 letters',
        loginSuccessfulEmail: 'Email has been sent.',
        loginUnSuccessfulEmail: 'Email has not sent.',
        loginWrongHeader: 'Something went wrong',
        loginWrongMessage: 'Please, check your information ant try again or sing up if you are new here!',
        //Registration page
        registrationTitle: 'Register to our page',
        registrationInformation: 'Your information',
        registrationUsername: 'Username',
        registrationEmail: 'Email',
        registrationType: 'User type',
        registrationVolunteer: 'Volunteer',
        registrationOrganization: 'Organization',
        registrationPassword: 'Password',
        registrationConfirm: 'Confirm password',
        registrationTerms: 'I accept terms and conditions!',
        registrationSingUp: 'Sing up',
        registrationRequiredMessage: 'This field is required and must contain at least 5 characters',
        registrationPasswordMisMatch: 'Password and confirm password do not match',
        registrationHaveAnAccount: 'I have an account',
        registrationValidEmail: 'Valid email is required',
        registrationNotRegisteredHeader: 'User was not registered',
        registrationNotRegisteredMessage: 'Please, check your information ant try again',
        registrationSuccess: 'User was registered successfully',
        //Projects page
        projectsSearch: 'Search',
        projectsArchive: 'ARCHIVE',
        projectsNew: 'NEW PROJECTS',
        projectsUntil: 'until',
        //Project page
        projectEdit: 'Edit project',
        projectVolunteers: 'Volunteers',
        projectFind: 'Find us at',
        projectSave: 'Save',
        projectsToVolunteer: 'I want to volunteer',
        projectSaved: 'Saved',
        projectsYouVolunteer: 'You volunteer in this project',
        projectStart: 'Project begins',
        projectEnd: 'Project ends',
        projectGoBack: 'Go back',
        projectHeader: 'Project page',
        //Volunteers page
        volunteersHeader: 'Volunteers page',
        volunteersYourVolunteers: 'Your project volunteers',
        volunteersAll: 'All registered users',
        volunteersNone: 'None',
        volunteersAnonymousName: 'Anonymous',
        volunteersAnonymousLast: 'user',
        volunteersGoBack: 'Go back',
        //Modal volunteer
        modalVAnonymous: 'Anonymous user',
        modalVContatInfo: 'Contact information',
        modalNone: 'None',
        modalVDescription: 'Description about activities',
        modalClose: 'Close',
        //New project
        newPojectHeader: 'New project',
        newPojectImage: 'Project image',
        newPojectTitle: 'Title',
        newPojectEmail: 'Email',
        newPojectPhone: 'Phone',
        newPojectWebsite: 'Website',
        newPojectDescription: 'Description',
        newPojectStart: 'Start date',
        newPojectEnd: 'End date',
        newPojectLocation: 'Loacation address',
        newPojectCreate: 'Create',
        newPojectAlertNotHeader: 'Project was not created',
        newPojectAlertNotMessage: 'Please, fill in empty gaps',
        newPojectAlertOk: 'OK',
        //Edit project
        editProjectDelete: 'DELETE',
        editProjectAlertEditHeader: 'Update failed',
        editProjectAlertEditMessage: 'Please, fill in an empty gaps',
        editHeader: 'Edit project',
        editTitle: 'Edit title',
        editDescription: 'Edit description',
        editChangeStart: 'Change start date',
        editChangeEnd: 'Change end date',
        changeLocation: 'Change location address',
        editSave: 'Save changes',
        editSucesfull: 'Sucesfully Saved!',
        editConfirmDelete: 'Are you sure want to delete this project?',
        yes: 'Yes',
        no: 'No',
        //registrationSuccess: 'User was registered successfully',
        //copyright
        cr1: 'Privacy Policy',
        cr2: 'volunteering.ga website refers to site hosted on the volunteering.ga. This privacy policy describes how volunteering.ga uses and protects any information that you give us. We are committed to ensuring that your privacy is protected. If you provide us with personal information through volunteering.ga, you can be assured that it will only be used in accordance with this privacy statement.',
        cr3: 'Website Visitors',
        cr4: 'Like most website operators, volunteering.ga collects non-personally-identifying information volunteering.ga also collects potentially personally-identifying information like Internet Protocol (IP) addresses. volunteering.ga does not use IP addresses to identify its visitors, however, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.',
        cr5: 'Gathering of Personally-Identifying Information',
        cr6: 'Certain visitors to volunteering.ga choose to interact with volunteering.ga in ways that require volunteering.ga to gather personally-identifying information. The amount and type of information that volunteering.ga gathers depends on the nature of the interaction. For example, we ask visitors who use our services to provide a username and email address.',
        cr7: 'In each case, volunteering.ga collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with volunteering.ga. volunteering.ga does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities, like viewing latest websites offers.',
        cr8: 'All of the information that is collected on volunteering.ga will be handled in accordance with GDPR legislation.',
        cr9: 'Protection of Certain Personally-Identifying Information',
        cr10: 'volunteering.ga discloses potentially personally-identifying and personally-identifying information only to those of project administrators, employees, contractors, and affiliated organizations that (i) need to know that information in order to process it on volunteering.ga’s behalf or to provide services available through volunteering.ga, and (ii) that have agreed not to disclose it to others.',
        cr11: 'volunteering.ga will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to project administrators, employees, contractors, and affiliated organizations, as described above, volunteering.ga discloses potentially personally-identifying and personally-identifying information only when required to do so by law, if you give permission to have your information shared, or when volunteering.ga believes in good faith that disclosure is reasonably necessary to protect the property or rights of volunteering.ga, third parties, or the public at large.',
        cr12: 'If you are a registered user of a volunteering.ga website and have supplied your email address, volunteering.ga may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with volunteering.ga and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum.',
        cr13: 'If you send us a request , we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. volunteering.ga takes all measures reasonably necessary to protect against the unauthorized access, use, alteration, or destruction of potentially personally-identifying and personally-identifying information.',
        cr14: 'Use of personal information',
        cr15: 'We use the information you provide to register for an account, attend our events, receive newsletters, use certain other services. We will not sell or lease your personal information to third parties unless we have your permission or are required by law to do so.',
        cr16: 'Legal grounds for processing personal information',
        cr17: 'We rely on one or more of the following processing conditions:',
        cr18: 'our legitimate interests in the effective delivery of information and services to you;',
        cr19: 'explicit consent that you have given;',
        cr20: 'legal obligations.',
        cr21: 'Access to data',
        cr22: 'You have the right to request a copy of the information we hold about you. If you would like a copy of some or all your personal information, please follow the instructions at the end of this policy.',
        cr23: 'volunteering.ga user account information can be retrived by following these steps:',
        cr24: '1.Visit https://login.volunteering.ga/, and enter your username and password.',
        cr25: '2.Go to account settings.',
        cr26: '3.Click “Send me my data”',
        cr27: 'Retention of personal information',
        cr28: 'We will retain your personal information on our systems only for as long as we need to, for the success of the TeamPlatypus project and the programs that support volunteering.ga. We keep contact information (such as mailing list information) until a user unsubscribes or requests that we delete that information from our live systems. If you choose to unsubscribe from a mailing list, we may keep certain limited information about you so that we may honor your request.',
        cr29: 'volunteering.ga will not delete personal data from logs or records necessary to the operation, development, or archives of the TeamPlatypus project.',
        cr30: 'volunteering.ga shall maintain attendee’s data for 3 months to better track and foster community growth, and then automatically delete non-essential data collected via registration. Attendee names and email addresses will be retained indefinitely, to preserve our ability to respond to code of conduct reports.',
        cr31: 'When deletion is requested or otherwise required, we will anonymise the data of data subjects and/or remove their information from publicly accessible sites if the deletion of data would break essential systems or damage the logs or records necessary to the operation, development, or archival records of the TeamPlatypus project.',
        cr32: 'If you would like to request deletion of your account and associated data, please follow these steps:',
        cr33: '1.Visit https://volunteering.ga/.',
        cr34: '2.Login and go to settings.',
        cr35: '3.Click “Request Permanent Account Deletion”.',
        cr36: 'Rights in relation to your information',
        cr37: 'You may have certain rights under data protection law in relation to the personal information we hold about you. In particular, you may have a right to:',
        cr38: 'request a copy of personal information we hold about you;',
        cr39: 'ask that we update the personal information we hold about you, or independently correct such personal information that you think is incorrect or incomplete;',
        cr40: 'ask that we delete personal information that we hold about you from live systems, or restrict the way in which we use such personal information (for information on deletion from archives, see the “Retention of personal information” section);',
        cr41: 'object to our processing of your personal information; and/or withdraw your consent to our processing of your personal information (to the extent such processing is based on consent and consent is the only permissible basis for processing).',
        cr42: 'Third Party Links',
        cr43: 'Our website may contain links to other websites provided by third parties not under our control. When following a link and providing information to a 3rd-party website, please be aware that we are not responsible for the data provided to that third party. This privacy policy only applies to the websites listed at the beginning of this document, so when you visit other websites, even when you click on a link posted on volunteering.ga, you should read their own privacy policies.',
        cr44: 'Cookies',
        cr45: 'Additionally, information about how you use our website is collected automatically using “cookies”. Cookies are text files placed on your computer to collect standard internet log information and visitor behaviour information. This information is used to track visitor use of the website and to compile statistical reports on website activity.',
        cr46: 'Privacy Policy Changes',
        cr47: 'Although most changes are likely to be minor, volunteering.ga may change its Privacy Policy from time to time, and at volunteering.ga’s sole discretion. volunteering.ga encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.',
        cr48: 'Contact',
        cr49: 'Please contact us if you have any questions about our privacy policy or information we hold about you by emailing teamPlatypus@volunteering.ga.',
        // Volunteers settings page
        volSettingsHeader: 'Volunteer Settings',
        volSettingsImage: 'Your image url',
        volSettingsName: 'Name',
        volSettingsLastName: 'Last Name',
        volSettingsPhone: 'Phone',
        volSettingsEmail: 'Email',
        volSettingsDescription: 'Description',
        volSettingsSaveChanges: 'Save changes',
        volSettingsAlertSuccess: 'Your changes were saved successfully',
        volSettingsAlertFail: "Your changes haven't been saved",
        //Change-password page
        changePassHeader: 'RESET YOUR PASSWORD',
        changePassFieldSet: 'Needed information',
        changePassEnterUserEmail: 'Enter user email',
        changePassOldPassword: 'Old password',
        changePassNewPassword: 'New password',
        changePassConfirmPassword: 'Confirm password',
        changePassButton: 'Change password',
        changePassGoBack: 'Changed your mind? Go back',
        changePassChangedSuccess: 'Your password was changed successfully',
        changePassChangeFail: "Your password haven't been changed",
        changePassFielRequired: 'This field is required',
        changePassContain5: 'This field is required and must contain at least 5 characters ',
        changePassPassDontMatch: 'Password and ConfirmPassword do not match'
    }
}