import { Lang } from '../models/Lang';

export class En {
    public static En: Lang = {
        // Side menu
        menuMain: 'Main',
        menuOrganizations: 'Organizations',
        menuProjects: 'Projects',
        menuSavedProjects: 'Saved projects',
        menuSelectedProjects: 'Selected projects',
        menuCreatedProjects: 'Created projects',
        menuNewProject: 'New project',
        menuCalendar: 'Calendar',
        menuAboutUs: 'About us',
        menuPrivacyPolicy: 'Privacy policy',
        menuLogin: 'Login',
        menuRegistration: 'Registration',
        menuSettings: 'Settings',
        menuMenu: 'Menu',
        menuLogout: 'Logout',
        // Main page
        mainTitle: 'Volunteering system',
        mainEvents: 'Upcoming events',
        mainWantedOrganizations: 'Most wanted organizations',
        //About us page
        aboutTitle: 'Shortly about us',
        aboutParag1: 'Platypus offers anyone an opportunity to immerse themselves in a community, working side by side with local leaders and tackle the most pressing challenges in Lithuania. Our mission is to help organizations all over Lithuania by providing them with manpower and funds needed in order to combat challenges facing our county‘s communities. We hope:',
        aboutParag2: "give something back to an organisation that has impacted on a person's life, either directly or indirectly",
        aboutParag3: 'make a difference to the lives of others',
        aboutParag4: 'help the environment',
        aboutParag5: 'help others less fortunate or without a voice feel valued and part of a team',
        aboutParag6: 'When you look at the reasons why volunteering is important, it’s not only about the impacts we can make in the lives of those less fortunate but the role it can play in making us more tolerant individuals and giving towards the global community. Each of us should be willing to offer our own time and expect nothing in return.',
        aboutTitle2: 'Why?',
        aboutVisit: 'Visit and find out more',
        aboutOpinion: 'Your opinion is important for us!',
        aboutButtonComment: 'Leave comment!',
        aboutButtonVideo: 'Watch video',
        aboutEnterEmail: 'Enter email',
        aboutFeelFree: 'Feel free to contact us',
        aboutComment: 'Comment',
        aboutRequired: 'Required field',
        aboutAlertCommentHeader: 'Thank you',
        aboutAlertCommentMessage: 'Your email has been submited',
        aboutSourceHeader: 'Want to know more?',
        aboutSourceMessage: 'Click confirm if you want to navigate to this page in a new tab',

        //Alert cancel and comfirm
        alertCancel: 'Cancel',
        alertConfirm: 'Confirm',
        toastClose: 'Close',
        //Login page
        loginWelcome: 'Welcome!',
        loginFieldset: 'Log in',
        loginUsername: 'Username',
        loginPassword: 'Password',
        loginForgot: 'Forgot you password?',
        loginButton: 'Sign in',
        loginNewHere: 'New here?',
        loginSignUp: 'Sing Up',
        loginResetPasswordMessage: 'Enter your email address to send a reset password link',
        loginRequiredField: 'Required field, must contain at least 5 letters',
        loginSuccessfulEmail: 'Email has been sent.',
        loginUnSuccessfulEmail: 'Email has not sent.',
        loginWrongHeader: 'Something went wrong',
        loginWrongMessage: 'Please, check your information ant try again or sing up if you are new here!',
        //Registration page
        registrationTitle: 'Register to our page',
        registrationInformation: 'Your information',
        registrationUsername: 'Username',
        registrationEmail: 'Email',
        registrationType: 'User type',
        registrationVolunteer: 'Volunteer',
        registrationOrganization: 'Organization',
        registrationPassword: 'Password',
        registrationConfirm: 'Confirm password',
        registrationTerms: 'I accept terms and conditions!',
        registrationSingUp: 'Sing up',
        registrationRequiredMessage: 'This field is required and must contain at least 5 characters',
        registrationPasswordMisMatch: 'Password and confirm password do not match',
        registrationHaveAnAccount: 'I have an account',
        registrationValidEmail: 'Valid email is required',
        registrationNotRegisteredHeader: 'User was not registered',
        registrationNotRegisteredMessage: 'Please, check your information ant try again',
        registrationSuccess: 'User was registered successfully'
    }
}