import { Lang } from '../models/Lang';

export class Lt {
    public static Lt: Lang = {
        // Side menu
        menuMain: 'Pagrindinis',
        menuOrganizations: 'Organizacijos',
        menuProjects: 'Projektai',
        menuSavedProjects: 'Išsaugoti projektai',
        menuSelectedProjects: 'Pasirinkti projektai',
        menuCreatedProjects: 'Sukurti projektai',
        menuNewProject: 'Naujas projektas',
        menuCalendar: 'Kalendorius',
        menuAboutUs: 'Apie mus',
        menuPrivacyPolicy: 'Privatumo politika',
        menuLogin: 'Prisijungti',
        menuRegistration: 'Registracija',
        menuSettings: 'Parametrai',
        menuMenu: 'Meniu',
        menuLogout: 'Atsijungti',
        // Main page
        mainTitle: 'Savanoriavimo sistema',
        mainEvents: 'Artimiausi projektai',
        mainWantedOrganizations: 'Populiariausios organizacijos',
        mainStart: 'Pradžia',
        mainIntroVideo: 'Apie sistemą',
        //About us page
        aboutTitle: 'Trumpai apie mus',
        aboutParag1: 'Platypus kiekvienam suteikia galimybę pasinerti į bendruomenę, dirbti kartu su vietos lyderiais ir spręsti svarbiausius iššūkius Lietuvoje. Mūsų misija - padėti organizacijoms visoje Lietuvoje, suteikiant jiems darbo jėgos ir lėšų, reikalingų kovoti su iššūkiais, su kuriais susiduria mūsų apskrities bendruomenės. Mes tikimės:',
        aboutParag2: 'padėti organizacijoms, kurios tiesiogiai ar netiesiogiai paveikė žmonių gyvenimus',
        aboutParag3: 'prisidėti prie kitų žmonių gyvenimo gerinimo',
        aboutParag4: 'padėti gerinti aplinką',
        aboutParag5: 'padėti mažiau pasisekusiems žmonėms ir mažumoms jaustis komandos dalimi ',
        aboutParag6: 'Kaip pažiūrime į priežastis kodėl savanoriavimas yra svarbus, , kalbame ne tik apie poveikį, kurį galime padaryti mažiau pasisekusių žmonių gyvenime, bet ir vaidmenį, kurį savanoriavimas gali atlikti, kad taptūmėme tolerantiškesni asmenys ir taptumėte bendruomeneškesni. Kiekvienas iš mūsų turėtų būti pasiruošęs pasiūlyti savo laiką ir nieko nesitikėti atgal.',
        aboutTitle2: 'Kodėl?',
        aboutVisit: 'Apsilankyk ir sužinosi daugiau!',
        aboutOpinion: 'Mums svarbu ką jūs manote!',
        aboutButtonComment: 'Palikite komentarą!',
        aboutButtonVideo: 'Žiūrėti vaizdo įrašą',
        aboutEnterEmail: 'Įveskite el paštą',
        aboutFeelFree: 'Laukiame jūsų nuomonės',
        aboutComment: 'Jūsų komentaras',
        aboutRequired: 'Šis laukas yra privalomas užpildyti',
        aboutAlertCommentHeader: 'Ačiū',
        aboutAlertCommentMessage: 'Jūsų laiškas sėkmingai išsiųstas',
        aboutSourceHeader: 'Norite sužinoti daugiau?',
        aboutSourceMessage: 'Paspauskite \'sutinku\' ir nuoroda atsidarys naujame lange',

        //Alert cancel and comfirm
        alertCancel: 'Atšaukti',
        alertConfirm: 'Sutikti',
        toastClose: 'Uždaryti',
        //Login page
        loginWelcome: 'Sveiki!',
        loginFieldset: 'Prisijunkite',
        loginUsername: 'Vartotojo vardas',
        loginPassword: 'Slaptažodis',
        loginForgot: 'Pamiršote slaptažodį?',
        loginButton: 'Prisijungti',
        loginNewHere: 'Pirmas kartas?',
        loginSignUp: ' Registruokitės',
        loginResetPasswordMessage: 'Įveskite savo el-pašto adresą ir mes jums atsiųsime slaptažodžio keitimo nuorodą ',
        loginRequiredField: 'Šis laukas privalomas ir turi turėti bent 5 simbolius',
        loginSuccessfulEmail: 'Laiškas buvo išsiųstas',
        loginUnSuccessfulEmail: 'Laiško nepavyko išsiųsti',
        loginWrongHeader: 'Prisijungti nepavyko',
        loginWrongMessage: 'Neteisingi prisijungimo vardas ir slaptažodis!',
        loginSuccessLogin:'Sėkmingai prisijungėte svetainėje',
        //Registration page
        registrationTitle: 'Susikurkite vartotojo paskyrą',
        registrationInformation: 'Jūsų informacija',
        registrationUsername: 'Vartotojo vardas',
        registrationEmail: 'El-paštas',
        registrationType: 'Vartotojo vardas',
        registrationVolunteer: 'Savanoris',
        registrationOrganization: 'Organizacija',
        registrationPassword: 'Slaptažodis',
        registrationConfirm: 'Patvirtinkit slaptažodį',
        registrationTerms: 'Sutinku su sąlygomis!',
        registrationSingUp: 'Registruotis',
        registrationRequiredMessage: 'Šis laukas privalomas ir turi turėti bent 5 simbolius',
        registrationPasswordMisMatch: 'Slaptažodžiai nesutampa',
        registrationHaveAnAccount: 'Aš jau prisiregistravęs!',
        registrationValidEmail: 'Validus el-paštas yra būtinas',
        registrationNotRegisteredHeader: 'Registracija nesėkminga',
        registrationNotRegisteredMessage: 'Įvesti duomenys neteisingi',
        registrationSuccess: 'Vartotojas sėkmingai priregistruotas',
        registrationEmailTaken: 'Šis el. paštas jau paimtas!',
        registrationUsernameTaken: 'Šis vartotojo vardas jau paimtas!',
        //Projects page
        projectsSearch: 'Paieška',
        projectsArchive: 'ARCHYVAS',
        projectsNew: 'NAUJI PROJEKTAI',
        projectsUntil: 'until',
        //Project page
        projectEdit: 'Redaguoti projektą',
        projectVolunteers: 'Savanoriai',
        projectFind: 'Mus rasite',
        projectSave: 'Išsaugoti',
        projectsToVolunteer: 'Aš noriu savanoriauti',
        projectSaved: 'Išsaugotas',
        projectsYouVolunteer: 'Jūs esate savanoris',
        projectStart: 'Projektas prasidės',
        projectEnd: 'Projektas baigsis',
        projectGoBack: 'Grįžti',
        projectHeader: 'Projekto puslapis',
        projectOpenInNewTab: 'Atidaryti naujame lange',
        projectClipBoard: 'Nukopijuoti į iškarpinę',
        //Volunteers page
        volunteersHeader: 'Savanorių puslpapis',
        volunteersYourVolunteers: 'Jūsų projekto savanoriai',
        volunteersAll: 'Visi užsiregistravę vartotojai',
        volunteersNone: 'Nėra informacijos',
        volunteersAnonymousName: 'Anoniminis ',
        volunteersAnonymousLast: 'vartotojas',
        volunteersGoBack: 'Grįžti',
        //Modal volunteer
        modalVAnonymous: 'Anoniminis vartotojas',
        modalVContatInfo: 'Kontaktinė informacija',
        modalNone: 'Nėra informacijos',
        modalVDescription: 'Aprašymas apie veiklas',
        modalClose: 'Uždaryti',
        //New project
        newPojectHeader: 'Naujas projektas',
        newPojectImage: 'Projekto paveikslėlis',
        newPojectTitle: 'Pavadinimas',
        newPojectEmail: 'El-pašto adresas',
        newPojectPhone: 'Telefono numeris',
        newPojectWebsite: 'Internetinis tinklapis',
        newPojectDescription: 'Aprašymas',
        newPojectStart: 'Pradžios data',
        newPojectEnd: 'Pabaigos data',
        newPojectLocation: 'Vietovės adresas',
        newPojectCreate: 'Sukurti',
        newPojectAlertNotHeader: 'Projektas nebuvo sukurtas',
        newPojectAlertNotMessage: 'Prašome užpildykite tuščius laukus',
        newPojectAlertOk: 'Gerai',
        newProjectFailedDates: 'Jūsų projekto pabaigos data yra ankstesnė nei pradžios',
        //Edit project
        editProjectDelete: 'Ištrinti',
        editProjectAlertEditHeader: 'Atnaujinimas nepavyko',
        editProjectAlertEditMessage: 'Prašome užpildyti tuščius laukelius',
        editHeader: 'Koreguoti projektą',
        editTitle: 'Redaguoti pavadinimą',
        editDescription: 'Redaguoti aprašą',
        editChangeStart: 'Keisti pradžios laiką',
        editChangeEnd: 'Keisti pabaigos laiką',
        changeLocation: 'Keisti vietovę',
        editSave: 'Išsaugoti pakeitimus',
        editSucesfull: 'Sėkmingai išsaugota',
        editConfirmDelete: 'Ar tikrai norite ištrinti šį projektą?',
        yes: 'Taip',
        no: 'Ne',
        //registrationSuccess: 'Vartotojas sėkmingai priregistruotas',
        //Copyright
        cr1: 'Privatumo politika',
        cr2: 'Ši privatumo politika apibūdina, kaip volunteering.ga naudoja ir saugo bet kokią mums suteiktą informaciją. Esame įsipareigoję užtikrinti, kad jūsų privatumas būtų apsaugotas. Jei pateikiate mums asmeninę informaciją per volunteering.ga, galite būti tikri, kad ji bus naudojama tik pagal šį privatumo pareiškimą.',
        cr3: 'Svetainės lankytojai',
        cr4: 'Kaip ir dauguma interneto svetainių operatorių, volunteering.ga renka ne asmeniškai identifikuojančią informaciją volunteering.ga taip pat renka potencialiai asmeniškai identifikuojančią informaciją, pvz., interneto protokolo (IP) adresus. volunteering.ga nenaudoja IP adresų, kad nustatytų savo lankytojus, ir neatskleidžia tokios informacijos, išskyrus tas pačias aplinkybes, kuriomis jis naudojasi ir atskleidžia asmeninę informaciją, kaip aprašyta toliau.',
        cr5: 'Asmens identifikavimo informacijos rinkimas',
        cr6: 'Tam tikri volunteering.ga lankytojai pasirenka sąveikauti su volunteering.ga tokiu būdu, kuris reikalauja volunteering.ga informacijos rinkimo. Informacijos, kurią volunteering.ga renka, kiekis ir rūšis priklauso nuo sąveikos pobūdžio. Pvz., Prašome lankytojų, kurie naudojasi mūsų paslaugomis, pateikti naudotojo vardą ir el. Pašto adresą.',
        cr7: 'Kiekvienu atveju volunteering.ga renka tokią informaciją tik tiek, kiek būtina ar tikslinga, siekiant įvykdyti lankytojo sąveiką su volunteering.ga. volunteering.ga neatskleidžia asmeniškai identifikuojančios informacijos, išskyrus žemiau aprašytą informaciją. Be to, lankytojai visada gali atsisakyti pateikti asmeniškai identifikuojančią informaciją, tačiau įspėjimas, kad jis gali užkirsti kelią tam tikrai su svetaine susijusiai veiklai, pavyzdžiui, peržiūrėti naujausius svetainės pasiūlymus.',
        cr8: 'Visa informacija, surinkta apie savanorišką veiklą, bus tvarkoma pagal GDPR teisės aktus.',
        cr9: 'Tam tikros asmeniškai identifikuojančios informacijos apsauga',
        cr10: 'volunteering.ga atskleidžia potencialiai asmeniškai identifikuojančią ir asmeniškai identifikuojančią informaciją tik projektų administratorių, darbuotojų, rangovų ir susijusių organizacijų informacijai, kuri (i) turi žinoti šią informaciją, kad galėtų ją apdoroti savanoriškoje veikloje. ir (ii) kurie sutiko neatskleisti jos kitiems. ',
        cr11: 'volunteering.ga  niekam neišnuomos ar parduos asmeniškai identifikuojančios ir asmeniškai identifikuojančios informacijos. Išskyrus projekto administratoriams, darbuotojams, rangovams ir susijusioms organizacijoms, kaip aprašyta aukščiau, savanorystė.ga atskleidžia potencialiai asmeniškai identifikuojančią ir asmeniškai identifikuojančią informaciją tik tada, kai to reikalauja įstatymas, jei suteikiate leidimą bendrai naudoti informaciją, arba, kai savanoriška veikla patikima, kad atskleidimas pagrįstai būtinas savanoriškos veiklos, trečiųjų šalių ar plačiosios visuomenės turtui ar teisėms apsaugoti.',
        cr12: 'Jei esate registruotas savanoriškos svetainės interneto svetainės vartotojas ir pateikėte savo el. Pašto adresą, volunteering.ga kartais gali atsiųsti jums el. Laišką, kuriame jums pasakys apie naujas funkcijas, prašyti atsiliepimų, arba tiesiog atnaujinti informaciją apie tai, kas vyksta su savanorišku verslu.ga ir mūsų produktais. ',
        cr13: 'Jei atsiunčiate mums užklausą, pasiliekame teisę paskelbti ją, kad galėtume paaiškinti ar atsakyti į jūsų prašymą arba padėti mums palaikyti kitus naudotojus. volunteering.ga imasi visų pagrįstai reikalingų priemonių apsaugoti nuo neteisėtos prieigos prie asmens tapatybės nustatymo ir asmens tapatybės nustatymo informacijos naudojimo, naudojimo ar pakeitimo.',
        cr14: 'Asmeninės informacijos naudojimas',
        cr15: 'Naudojame jūsų pateiktą informaciją, kad galėtumėte užsiregistruoti paskyroje, dalyvauti mūsų renginiuose, gauti informacinius pranešimus. Mes neparduosime ir neišnuomosime jūsų asmeninės informacijos trečiosioms šalims, nebent mes turėtume jūsų leidimą arba pagal įstatymą to reikalaujame.',
        cr16: 'Asmens informacijos tvarkymo teisinis pagrindas',
        cr17: 'Mes pasikliaujame viena ar keliomis iš šių apdorojimo sąlygų:',
        cr18: 'mūsų teisėtus interesus veiksmingai teikti informaciją ir paslaugas jums;',
        cr19: 'aiškus sutikimas, kurį suteikėte;',
        cr20: 'teisinius įsipareigojimus.',
        cr21: 'Prieiga prie duomenų',
        cr22: 'Jūs turite teisę prašyti informacijos, kurią mes laikome apie jus. Jei norite kopijuoti kai kurias ar visas savo asmeninę informaciją, vadovaukitės šios politikos pabaigoje pateiktomis instrukcijomis',
        cr23: 'savanoriškos informacijos apie naudotojo paskyros informaciją galima atgauti atlikus šiuos veiksmus:',
        cr24: '1.Apsilankant https://volunteering.ga/login ir įveskite savo vartotojo vardą ir slaptažodį.',
        cr25: '2.Prisijunkite prie paskyros nustatymų.',
        cr26: '3. Spustelėkite „Siųsti man mano duomenis“',
        cr27: 'Asmens informacijos saugojimas',
        cr28: 'Mes išsaugosime jūsų asmeninę informaciją apie mūsų sistemas tik tiek, kiek mums reikia, kad „TeamPlatypus“ projektas ir programos, palaikančios volunteering.ga, būtų sėkmingos. Mes saugome kontaktinę informaciją (pvz., Informaciją apie adresų sąrašą), kol vartotojas atsisako arba prašo ištrinti šią informaciją iš mūsų sistemų. Jei nuspręsite atsisakyti prenumeratos sąrašo, galime saugoti tam tikrą ribotą informaciją apie jus, kad galėtume įvykdyti jūsų prašymą.',
        cr29: 'volunteering.ga neištrins asmeninių duomenų iš žurnalų ar įrašų, reikalingų TeamPlatypus projekto veikimui, kūrimui ar archyvui.',
        cr30: 'volunteering.ga saugo dalyvių duomenis 3 mėnesius, kad galėtų geriau stebėti ir skatinti bendruomenės augimą, ir automatiškai ištrinti nereikalingus duomenis, surinktus registruojant. Dalyvių vardai ir el. Pašto adresai bus išsaugoti neribotą laiką, kad galėtume atsakyti į elgesio kodekso ataskaitas.',
        cr31: 'Jei ištrinti prašoma ar kitaip reikalaujama, mes anonimizuosime duomenų subjektų duomenis ir / arba pašalinsime jų informaciją iš viešai prieinamų svetainių, jei duomenų ištrynimas nutrauktų esmines sistemas arba pažeistų žurnalus ar įrašus, reikalingus veiklai, plėtrai ar archyvavimui „TeamPlatypus“ projekto įrašai.',
        cr32: 'Jei norite prašyti ištrinti paskyrą ir susijusius duomenis, atlikite šiuos veiksmus:',
        cr33: '1.Apsilankykite https://volunteering.ga/.',
        cr34: '2. Prisijunkite ir eikite į nustatymus.',
        cr35: '3. Paspauskite „Prašyti paskyros ištrynimo“.',
        cr36: 'Su jūsų informacija susijusios teisės',
        cr37: 'Jūs galite turėti tam tikras teises pagal duomenų apsaugos įstatymus dėl asmeninės informacijos, kurią mes laikome apie jus. Visų pirma, jūs galite turėti teisę:',
        cr38: 'prašyti asmeninės informacijos, kurią mes laikome, kopiją;',
        cr39: 'paprašyti atnaujinti asmeninę informaciją, kurią mes laikome apie jus, arba savarankiškai ištaisyti tokią asmeninę informaciją, kuri, jūsų manymu, yra neteisinga ar neišsami;',
        cr40: 'paprašyti, kad mes ištrintume asmeninę informaciją, kurią mes laikome apie jus iš sistemų, arba apriboti būdą, kuriuo mes naudojame tokią asmeninę informaciją (informacijos apie išbraukimą iš archyvų, žr. skyrių „Asmeninės informacijos saugojimas“);',
        cr41: 'prieštarauja mūsų asmens duomenų tvarkymui; ir / arba atšaukti savo sutikimą tvarkyti jūsų asmeninę informaciją (tiek, kiek toks apdorojimas yra pagrįstas sutikimu ir sutikimu, yra vienintelis leistinas tvarkymo pagrindas).',
        cr42: 'Trečiųjų šalių nuorodos',
        cr43: 'Mūsų tinklalapyje gali būti nuorodų į kitas svetaines, kurias teikia mūsų kontroliuojamos trečiosios šalys. Atsižvelkite į nuorodą ir pateikdami informaciją trečiosios šalies tinklapyje, atkreipkite dėmesį, kad mes neatsakome už trečiajai šaliai pateiktus duomenis. Ši privatumo politika taikoma tik svetainėms, išvardytoms šio dokumento pradžioje, todėl, kai lankotės kitose svetainėse, net kai spustelėsite nuorodą, paskelbtą volunteering.ga, turėtumėte perskaityti jų privatumo politiką.',
        cr44: 'Slapukai',
        cr45: 'Be to, informacija apie tai, kaip jūs naudojatės mūsų svetaine, renkama automatiškai naudojant „slapukus“. Slapukai - tai jūsų kompiuteryje esantys tekstiniai failai, skirti rinkti standartinę interneto žurnalo informaciją ir informaciją apie lankytojų elgesį. Ši informacija naudojama stebint svetainės lankytojų naudojimą ir rengiant statistines ataskaitas apie svetainės veiklą.',
        cr46: 'Privatumo politikos pakeitimai',
        cr47: 'Nors dauguma pakeitimų gali būti nedideli, volunteering.ga kartais gali keisti savo privatumo politiką ir volunteering.ga skatina lankytojus dažnai patikrinti šį puslapį dėl bet kokių jo privatumo politikos pakeitimų. Jūsų tęstinis šio tinklalapio naudojimas po bet kokių šios privatumo politikos pakeitimų bus jūsų pritarimas tokiems pakeitimams.',
        cr48: 'Kontaktai',
        cr49: 'Prašome susisiekti su mumis, jei turite kokių nors klausimų apie mūsų privatumo politiką ar informaciją, kurią mes laikome apie jus elektroniniu paštu teamPlatypus@volunteering.ga.',
        crVisit: '1. Apsilankykite',
        crEnter: ' ir įveskite savo vartotojo vardą ir slaptažodį',
        // Volunteers settings page
        volSettingsHeader: 'Savanario parametrų keitimas',
        volSettingsImage: 'Jūsų nuotraukos nuoroda',
        volSettingsName: 'Vardas',
        volSettingsLastName: 'Pavardė',
        volSettingsPhone: 'Telefono numeris',
        volSettingsEmail: 'El-pašto adresas',
        volSettingsDescription: 'Aprašas apie jus',
        volSettingsSaveChanges: 'Išsaugoti pakeitimus',
        volSettingsAlertSuccess: 'Pakeitimai išsaugoti sėkmingai',
        volSettingsAlertFail: 'Pakeitimų išsaugoti nepavyko',
        volSettingsChangePass: 'Pakeisti slaptažodį',
        volSettingsDeleteAcc: 'Ištrinti paskyrą',
        volSettingsCannotGetVolunteer: 'Negalime užkrauti Jūsų duomenų iš duomenų bazės',
        //Change-password page
        changePassHeader: 'PASIKEISKITE SLAPTAŽODĮ',
        changePassFieldSet: 'Reikalinga informacija ',
        changePassEnterUserEmail: 'Įveskite vartotojo el-paštą',
        changePassOldPassword: 'Senas slaptažodis',
        changePassNewPassword: 'Naujas slaptažodis',
        changePassConfirmPassword: 'Patvirtinkite slaptažodį',
        changePassButton: 'Keisti slaptažodį',
        changePassGoBack: 'Persigalvojote? Grįžkite atgal',
        changePassChangedSuccess: 'Slaptažodis pakeistas sėkmingai',
        changePassChangeFail: 'Slaptažodžio pakeisti nepavyko',
        changePassFielRequired: 'Šis laukas yra privalomas',
        changePassContain5: 'Šis laukas yra privalomas ir turi būti sudarytas bent iš 5 simbolių',
        changePassPassDontMatch: 'Slaptažodžiai nesutampa',

        // Organization settings page
        orgSettingsHeader: 'Organizacijos parametrų keitimas',
        orgSettingsWebsite: 'Organizacijos puslapis',
        orgSettingsImage: 'Jūsų nuotraukos nuoroda',
        orgSettingsTitle: 'Organizacijos pavadinimas',
        orgSettingsAddress: 'Adresas',
        orgSettingsPhone: 'Telefonas',
        orgSettingsEmail: 'El-pašto adresas',
        orgSettingsDescription: 'Jūsų aprašas',
        orgSettingsSaveChanges: 'Išsaugoti pakeitimus',
        orgSettingsAlertSuccess: 'Pakeitimai išsaugoti sėkmingai',
        orgSettingsAlertFail: 'Pakeitimų išsaugoti nepavyko',
        orgSettingsChangePass: 'Pakeisti slaptažodį',
        orgSettingsDeleteAcc: 'Ištrinti paskyrą',
        orgSettingsDeleteAalert: 'Jūs pasirinkote ištrinti savo paskyrą',
        orgSettingsDeleteConfirm: 'Ar tikrai norite ją ištrinti?',
        orgSettingsDeleteButton: 'Taip',
        orgSettingsAlertConfirm: 'Gerai',
        orgSettingsDeleteCancel: 'Grįžti',
        orgSettingsDeleted: 'Paskyra ištrinta',
        orgSettingsCannotGetOrganization: 'Negalime užkrauti Jūsų duomenų iš duomenų bazės',
        orgRequiredField3: 'Šis laukas yra privalomas ir turi būti sudarytas bent iš trijų simbolių',
        orgRequiredEmail: 'Šis laukas yra privalomas ir validus el-pašto adresas turi būti pateiktas',
        orgCaution: 'Pavadinimo, nuotraukos ir jūsų organizacijos el-paštas yra privalomi norint, kad jūsų organizacija būtų matoma organizacijų sąraše',
        orgSuccessUpdate: 'Informacija sėkmingai atnaujinta',
        orgFailUpdate: 'Informacijos atnaujinimas nepavyko',
        // Organization page
        orgHeader: 'Organizacijos puslapis',
        orgGoToProject: 'Eiti į projekto puslapį',
        orgClipBoard: 'Nukopijuota į iškarpinę',
        orgFindUs: 'Mus galite rasti',
        orgComment: 'Komentuoti',
        orgComments: 'Komentarai',
        orgDelComment: 'Ištrinti komentarą',
        orgProjects: 'Projektai',
        orgNoComments: ' Komentarų nėra',
        orgNoProjects: 'Projektų nėra',
        orgsHeader: 'Organizacijos',
        //Not found page
        notFoundh2: ' Puslapis nerastas',
        notFoundpar: 'Puslapis, kurio ieškote, nerastas. Galbūt jis buvo ištrintas, pasikeitė jo pavadinimas arba jis tapo laikinai neprieinamas',
        notFoundGoMain: 'Grįžkite į pagrindinį puslapį',

        // Toast messages
        toastDeletedSuccessfuly: 'Projektas sėkmingai pašalintas!',
        toastFailedToDelete: 'Projekto nepavyko pašalinti!',
        toastUpdatedSuccessfuly: 'Projektas sėkmingai atnaujintas!',
        toastFailedToUpdate: 'Projekto atnaujinti nepavyko!',
        toastEmailWasNotSent: 'Elektroninis laiškas nebuvo išsiųstas!',
        toastEmailWasSent: 'Elektroninis laiškas sėkmingai išsiųstas!',

        // Calendar page
        calFrom: 'Nuo',
        calTo: 'Iki',
        calToday: 'Šiandien'
    }
}
