import { Lang } from '../models/Lang';

export class Lt {
    public static Lt: Lang = {
        // Side menu
        menuMain: 'Pagrindinis',
        menuOrganizations: 'Organizacijos',
        menuProjects: 'Projektai',
        menuSavedProjects: 'Išsaugoti projektai',
        menuSelectedProjects: 'Pasirinkti projektai',
        menuCreatedProjects: 'Sukurti projektai',
        menuNewProject: 'Naujas projektas',
        menuCalendar: 'Kalendorius',
        menuAboutUs: 'Apie mus',
        menuPrivacyPolicy: 'Privatumo politika',
        menuLogin: 'Prisijungti',
        menuRegistration: 'Registracija',
        menuSettings: 'Parametrai',
        menuMenu: 'Meniu',
        menuLogout: 'Atsijungti',
        // Main page
        mainTitle: 'Savanoriavimo sistema',
        mainEvents: 'Artimiausi projektai',
        mainWantedOrganizations: 'Populiariausios organizacijos',
        mainStart: 'Pradžia',
        //About us page
        aboutTitle: 'Trumpai apie mus',
        aboutParag1: 'Platypus offers anyone an opportunity to immerse themselves in a community, working side by side with local leaders and tackle the most pressing challenges in Lithuania. Our mission is to help organizations all over Lithuania by providing them with manpower and funds needed in order to combat challenges facing our county‘s communities. We hope:',
        aboutParag2: "give something back to an organisation that has impacted on a person's life, either directly or indirectly",
        aboutParag3: 'make a difference to the lives of others',
        aboutParag4: 'help the environment',
        aboutParag5: 'help others less fortunate or without a voice feel valued and part of a team',
        aboutParag6: 'When you look at the reasons why volunteering is important, it’s not only about the impacts we can make in the lives of those less fortunate but the role it can play in making us more tolerant individuals and giving towards the global community. Each of us should be willing to offer our own time and expect nothing in return.',
        aboutTitle2: 'Kodėl?',
        aboutVisit: 'Apsilankyk ir sužinosi daugiau!',
        aboutOpinion: 'Mums svarbu ką jūs manote!',
        aboutButtonComment: 'Palikite komentarą!',
        aboutButtonVideo: 'Žiūrėti vaizdo įrašą',
        aboutEnterEmail: 'Įveskite el paštą',
        aboutFeelFree: 'Laukiame jūsų nuomonės',
        aboutComment: 'Jūsų komentaras',
        aboutRequired: 'Šis laukas yra privalomas užpildyti',
        aboutAlertCommentHeader: 'Ačiū',
        aboutAlertCommentMessage: 'Jūsų laiškas sėkmingai išsiųstas',
        aboutSourceHeader: 'Norite sužinoti daugiau?',
        aboutSourceMessage: 'Paspauskite "sutinku" ir nuoroda atsidarys naujame lange',

        //Alert cancel and comfirm
        alertCancel: 'Atšaukti',
        alertConfirm: 'Sutikti',
        toastClose: 'Uždaryti',
        //Login page
        loginWelcome: 'Sveiki!',
        loginFieldset: 'Prisijunkite',
        loginUsername: 'Vartotojo vardas',
        loginPassword: 'Slaptažodis',
        loginForgot: 'Pamiršote slaptažodį?',
        loginButton: 'Prisijungti',
        loginNewHere: 'Pirmas kartas?',
        loginSignUp: ' Registruokitės',
        loginResetPasswordMessage: 'Įveskite savo el-pašto adresą ir mes jums atsiųsime slaptažodžio keitimo nuorodą ',
        loginRequiredField: 'Šis laukas privalomas ir turi turėti bent 5 simbolius',
        loginSuccessfulEmail: 'Laiškas buvo išsiųstas',
        loginUnSuccessfulEmail: 'Laiško nepavyko išsiųsti',
        loginWrongHeader: 'Prisijungti nepavyko',
        loginWrongMessage: 'Patikrinkite ar suvesti duomenys yra teisingi, o gal jums reikia užsiregistruoti?',
        //Registration page
        registrationTitle: 'Susikurkite vartotojo paskyrą',
        registrationInformation: 'Jūsų informacija',
        registrationUsername: 'Vartotojo vardas',
        registrationEmail: 'El-paštas',
        registrationType: 'Vartotojo vardas',
        registrationVolunteer: 'Savanoris',
        registrationOrganization: 'Organizacija',
        registrationPassword: 'Slaptažodis',
        registrationConfirm: 'Patvirtinit slaptažodį',
        registrationTerms: 'Sutinku su sąlygomis!',
        registrationSingUp: 'Registruotis',
        registrationRequiredMessage: 'Šis laukas privalomas ir turi turėti bent 5 simbolius',
        registrationPasswordMisMatch: 'Slaptažodžiai nesutampa',
        registrationHaveAnAccount: 'Aš jau prisiregistravęs!',
        registrationValidEmail: 'Validus el-paštas yra būtinas',
        registrationNotRegisteredHeader: 'Registracija nesėkminga',
        registrationNotRegisteredMessage: 'Prašome patikrinti informaciją ir bandyti dar kartą',
        registrationSuccess: 'Vartotojas sėkmingai priregistruotas',
        //Projects page
        projectsSearch: 'Paieška',
        projectsArchive: 'ARCHYVAS',
        projectsNew: 'NAUJI PROJEKTAI',
       //Project page
        projectEdit: 'Redaguoti projektą',
        projectVolunteers: 'Savanoriai',
        projectFind: 'Mus rasite',
        projectSave: 'Išsaugoti',
        projectsToVolunteer: 'Aš noriu savanoriauti',
        projectSaved: 'Išsaugotas',
        projectsYouVolunteer: 'Jūs esate savanoris',
        projectStart: 'Projektas prasidės',
        projectEnd: 'Projektas baigsis',
        projectGoBack: 'Grįžti',
        projectHeader: 'Projekto puslapis',
        //Volunteers page
        volunteersHeader: 'Savanorių puslpapis',
        volunteersYourVolunteers: 'Jūsų projekto savanoriai',
        volunteersAll: 'Visi užsiregistravę vartotojai',
        volunteersNone: 'Nėra informacijos',
        volunteersAnonymous: 'Anoniminis vartotojas',
        volunteersGoBack: 'Grįžti',
        //Modal volunteer
        modalVAnonymous: 'Anoniminis vartotojas',
        modalVContatInfo: 'Kontaktinė informacija',
        modalNone: 'Nėra informacijos',
        modalVDescription: 'Aprašymas apie veiklas',
        modalClose: 'Uždaryti'    
    }
}