export class Lang {
    // Side menu
    public menuMain: string;
    public menuOrganizations: string;
    public menuProjects: string;
    public menuSavedProjects: string;
    public menuSelectedProjects: string;
    public menuCreatedProjects: string;
    public menuNewProject: string;
    public menuCalendar: string;
    public menuAboutUs: string;
    public menuPrivacyPolicy: string;
    public menuLogin: string;
    public menuRegistration: string;
    public menuSettings: string;
    public menuMenu: string;
    public menuLogout: string;
    // Main page
    public mainTitle: string;
    public mainEvents: string;
    public mainWantedOrganizations: string;
    //About us
    public aboutTitle: string;
    public aboutTitle2: string;
    public aboutParag1: string;
    public aboutParag2: string;
    public aboutParag3: string;
    public aboutParag4: string;
    public aboutParag5: string;
    public aboutParag6: string;
    public aboutVisit: string;
    public aboutOpinion: string;
    public aboutButtonComment: string;
    public aboutButtonVideo: string;
    public aboutEnterEmail: string;
    public aboutFeelFree: string;
    public aboutComment: string;
    public aboutRequired: string;
    public aboutAlertCommentHeader: string;
    public aboutAlertCommentMessage: string;
    public aboutSourceHeader: string;
    public aboutSourceMessage: string;
    //Alert cancel and comfirm
    public alertCancel: string;
    public alertConfirm: string;
    public toastClose: string;
    //Login page
    public loginWelcome: string;
    public loginFieldset: string;
    public loginUsername: string;
    public loginPassword: string;
    public loginForgot: string;
    public loginButton: string;
    public loginNewHere: string;
    public loginSignUp: string;
    public loginResetPasswordMessage: string;
    public loginRequiredField: string;
    public loginSuccessfulEmail: string;
    public loginUnSuccessfulEmail: string;
    public loginWrongHeader: string;
    public loginWrongMessage: string;
    //Registration page
    public registrationTitle: string;
    public registrationInformation: string;
    public registrationUsername: string;
    public registrationEmail: string;
    public registrationType: string;
    public registrationVolunteer: string;
    public registrationOrganization: string;
    public registrationPassword: string;
    public registrationConfirm: string;
    public registrationTerms: string;
    public registrationSingUp: string;
    public registrationRequiredMessage: string;
    public registrationPasswordMisMatch: string;
    public registrationHaveAnAccount: string;
    public registrationValidEmail: string;
    public registrationNotRegisteredHeader: string;
    public registrationNotRegisteredMessage: string;
    public registrationSuccess: string;

}
